### ISSUE TITLE
only 775MB available as storage 

### ISSUE THREAD

**Issue by ghost** [xen0n/android_device_meizu_arale#20]
I flashed my Meizu Mx4 Ubuntu Edition with the CM13.0 20160821 build, but android detects only 775MB as available storage.  I flashed the mx4 build. I tried different recoverys (twrp 2.8.6.0 and a newer version) but the available storage is always limited.

**Comment by xen0n** [comment]
Oh crap I noticed that **immediately** after I flashed the _very first_ CM13.0 on my primary phone. Still have no idea why everything is taking up so much space. But isn't 775MB a little bit too small? You may have to flash the `arale` variant instead because my total space is like several gigabytes. The partition layouts are different.

**Comment by ghost** [comment]
I can only install the mx4 version of the rom with twrp 2.8.6.0. I tried the aral version of the rom with cyanogen recovery, but I had the same problem. The recoverys itself show only 775MB as available storage, too. As the phone has 16gb of storage, there there should be much more storage available. Do I have to change something at the partition layout, as I am coming from Ubuntu phone?

**Comment by ghost** [comment]
I just found a solution. I flashed the boot.img of an ubuntu phone image, tried to boot and than flashed the boot.img of this rom again and now I have 11.68 GB available storage.
The issue can be closed.

**Comment by xen0n** [comment]
@jonubulin Glad your problem is solved! Yes I just remembered that the Ubuntu OTA update will do the equivalent of `dd` on the raw partition, hence writing the correctly sized filesystem image.
