### ISSUE TITLE
Sorry to pop in, but how did you manage to get policyversion down to 29?

### ISSUE THREAD

**Issue by Packmaan7144** [xen0n/android_device_meizu_arale#23]
I have a hard time finding it in your commits, I am facinga similar issue.. Hope you can respond

**Comment by xen0n** [comment]
Hi,

My commits related to SELinux are all [here](https://github.com/CyanogenMod/android_external_sepolicy/compare/cm-13.0...xen0n:cm-13.0-policyvers-29). Basically you have to somehow revert all commits since the minimum version upgrade... With the AOSP version going up and up this is becoming really difficult. I haven't touched my codebase since last year due to academics, maybe you have to do the reverts yourself.

Anyway, good luck porting!

**Comment by Packmaan7144** [comment]
So if I apply all your commits to external/sepolicy, I would be at version 29? Do you know about 26?

**Comment by xen0n** [comment]
Sorry but my commits are all too ancient (they came from the `cm-13.0` era when I paused porting). You have to do the reverts yourself AFAIK, or you may look for some other repos with that work done. I didn't know anything about version 26, maybe that's a KK-era kernel blob? The approach is the same, only maybe the difficulty is too high for anyone to even try.

**Comment by Packmaan7144** [comment]
ok thank you
